/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HemDslUiModule extends AbstractHemDslUiModule {

	public HemDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
