/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class HemDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//  elements+=Element*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=Element*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_0() { return cElementsElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRuleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Element:
		//    Declaration
		//  | Rule
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  Declaration
		//| Rule
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Declaration
		public RuleCall getDeclarationParserRuleCall_0() { return cDeclarationParserRuleCall_0; }
		
		//Rule
		public RuleCall getRuleParserRuleCall_1() { return cRuleParserRuleCall_1; }
	}
	public class DeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Declaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplianceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeApplianceTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Declaration:
		//  'appliance' name=ID ':' type=ApplianceType ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'appliance' name=ID ':' type=ApplianceType ';'
		public Group getGroup() { return cGroup; }
		
		//'appliance'
		public Keyword getApplianceKeyword_0() { return cApplianceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=ApplianceType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//ApplianceType
		public RuleCall getTypeApplianceTypeEnumRuleCall_3_0() { return cTypeApplianceTypeEnumRuleCall_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cWhenKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionExprParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cThenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cThenActionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cThenActionActionParserRuleCall_5_0 = (RuleCall)cThenActionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cElseKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cElseActionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cElseActionActionParserRuleCall_6_1_0 = (RuleCall)cElseActionAssignment_6_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Rule:
		//  'rule' name=ID
		//  'when' condition=Expr
		//  'then' thenAction=Action
		//  ('else' elseAction=Action)?
		//  ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' name=ID
		//'when' condition=Expr
		//'then' thenAction=Action
		//('else' elseAction=Action)?
		//';'
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'when'
		public Keyword getWhenKeyword_2() { return cWhenKeyword_2; }
		
		//condition=Expr
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Expr
		public RuleCall getConditionExprParserRuleCall_3_0() { return cConditionExprParserRuleCall_3_0; }
		
		//'then'
		public Keyword getThenKeyword_4() { return cThenKeyword_4; }
		
		//thenAction=Action
		public Assignment getThenActionAssignment_5() { return cThenActionAssignment_5; }
		
		//Action
		public RuleCall getThenActionActionParserRuleCall_5_0() { return cThenActionActionParserRuleCall_5_0; }
		
		//('else' elseAction=Action)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'else'
		public Keyword getElseKeyword_6_0() { return cElseKeyword_6_0; }
		
		//elseAction=Action
		public Assignment getElseActionAssignment_6_1() { return cElseActionAssignment_6_1; }
		
		//Action
		public RuleCall getElseActionActionParserRuleCall_6_1_0() { return cElseActionActionParserRuleCall_6_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTurnActionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSetActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Action:
		//    TurnAction
		//  | SetAction
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  TurnAction
		//| SetAction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TurnAction
		public RuleCall getTurnActionParserRuleCall_0() { return cTurnActionParserRuleCall_0; }
		
		//SetAction
		public RuleCall getSetActionParserRuleCall_1() { return cSetActionParserRuleCall_1; }
	}
	public class TurnActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.TurnAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTurnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cApplianceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cApplianceDeclarationCrossReference_1_0 = (CrossReference)cApplianceAssignment_1.eContents().get(0);
		private final RuleCall cApplianceDeclarationIDTerminalRuleCall_1_0_1 = (RuleCall)cApplianceDeclarationCrossReference_1_0.eContents().get(1);
		private final Assignment cActionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cActionAlternatives_2_0 = (Alternatives)cActionAssignment_2.eContents().get(0);
		private final Keyword cActionOnKeyword_2_0_0 = (Keyword)cActionAlternatives_2_0.eContents().get(0);
		private final Keyword cActionOffKeyword_2_0_1 = (Keyword)cActionAlternatives_2_0.eContents().get(1);
		
		//TurnAction:
		//  'turn' appliance=[Declaration] action=('on'|'off')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'turn' appliance=[Declaration] action=('on'|'off')
		public Group getGroup() { return cGroup; }
		
		//'turn'
		public Keyword getTurnKeyword_0() { return cTurnKeyword_0; }
		
		//appliance=[Declaration]
		public Assignment getApplianceAssignment_1() { return cApplianceAssignment_1; }
		
		//[Declaration]
		public CrossReference getApplianceDeclarationCrossReference_1_0() { return cApplianceDeclarationCrossReference_1_0; }
		
		//ID
		public RuleCall getApplianceDeclarationIDTerminalRuleCall_1_0_1() { return cApplianceDeclarationIDTerminalRuleCall_1_0_1; }
		
		//action=('on'|'off')
		public Assignment getActionAssignment_2() { return cActionAssignment_2; }
		
		//('on'|'off')
		public Alternatives getActionAlternatives_2_0() { return cActionAlternatives_2_0; }
		
		//'on'
		public Keyword getActionOnKeyword_2_0_0() { return cActionOnKeyword_2_0_0; }
		
		//'off'
		public Keyword getActionOffKeyword_2_0_1() { return cActionOffKeyword_2_0_1; }
	}
	public class SetActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.SetAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cApplianceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cApplianceDeclarationCrossReference_1_0 = (CrossReference)cApplianceAssignment_1.eContents().get(0);
		private final RuleCall cApplianceDeclarationIDTerminalRuleCall_1_0_1 = (RuleCall)cApplianceDeclarationCrossReference_1_0.eContents().get(1);
		private final Keyword cToKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueNUMBERTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//SetAction:
		//  'set' appliance=[Declaration] 'to' value=NUMBER
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'set' appliance=[Declaration] 'to' value=NUMBER
		public Group getGroup() { return cGroup; }
		
		//'set'
		public Keyword getSetKeyword_0() { return cSetKeyword_0; }
		
		//appliance=[Declaration]
		public Assignment getApplianceAssignment_1() { return cApplianceAssignment_1; }
		
		//[Declaration]
		public CrossReference getApplianceDeclarationCrossReference_1_0() { return cApplianceDeclarationCrossReference_1_0; }
		
		//ID
		public RuleCall getApplianceDeclarationIDTerminalRuleCall_1_0_1() { return cApplianceDeclarationIDTerminalRuleCall_1_0_1; }
		
		//'to'
		public Keyword getToKeyword_2() { return cToKeyword_2; }
		
		//value=NUMBER
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//NUMBER
		public RuleCall getValueNUMBERTerminalRuleCall_3_0() { return cValueNUMBERTerminalRuleCall_3_0; }
	}
	public class ExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Expr");
		private final Assignment cOrExprAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cOrExprOrExprParserRuleCall_0 = (RuleCall)cOrExprAssignment.eContents().get(0);
		
		//Expr:
		//  orExpr=OrExpr
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//orExpr=OrExpr
		public Assignment getOrExprAssignment() { return cOrExprAssignment; }
		
		//OrExpr
		public RuleCall getOrExprOrExprParserRuleCall_0() { return cOrExprOrExprParserRuleCall_0; }
	}
	public class OrExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.OrExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftAndExprParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cOrKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightAndExprParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//OrExpr:
		//  left=AndExpr ( 'or' right+=AndExpr )*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//left=AndExpr ( 'or' right+=AndExpr )*
		public Group getGroup() { return cGroup; }
		
		//left=AndExpr
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//AndExpr
		public RuleCall getLeftAndExprParserRuleCall_0_0() { return cLeftAndExprParserRuleCall_0_0; }
		
		//( 'or' right+=AndExpr )*
		public Group getGroup_1() { return cGroup_1; }
		
		//'or'
		public Keyword getOrKeyword_1_0() { return cOrKeyword_1_0; }
		
		//right+=AndExpr
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//AndExpr
		public RuleCall getRightAndExprParserRuleCall_1_1_0() { return cRightAndExprParserRuleCall_1_1_0; }
	}
	public class AndExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.AndExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftPrimParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAndKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightPrimParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//AndExpr:
		//  left=Prim ( 'and' right+=Prim )*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//left=Prim ( 'and' right+=Prim )*
		public Group getGroup() { return cGroup; }
		
		//left=Prim
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//Prim
		public RuleCall getLeftPrimParserRuleCall_0_0() { return cLeftPrimParserRuleCall_0_0; }
		
		//( 'and' right+=Prim )*
		public Group getGroup_1() { return cGroup_1; }
		
		//'and'
		public Keyword getAndKeyword_1_0() { return cAndKeyword_1_0; }
		
		//right+=Prim
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Prim
		public RuleCall getRightPrimParserRuleCall_1_1_0() { return cRightPrimParserRuleCall_1_1_0; }
	}
	public class PrimElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.Prim");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cTimeCondAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cTimeCondTimeCondParserRuleCall_0_0 = (RuleCall)cTimeCondAssignment_0.eContents().get(0);
		private final Assignment cPriceCondAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cPriceCondPriceCondParserRuleCall_1_0 = (RuleCall)cPriceCondAssignment_1.eContents().get(0);
		private final Assignment cOccCondAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cOccCondOccCondParserRuleCall_2_0 = (RuleCall)cOccCondAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSubExprAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSubExprExprParserRuleCall_3_1_0 = (RuleCall)cSubExprAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Prim:
		//    timeCond=TimeCond
		//  | priceCond=PriceCond
		//  | occCond=OccCond
		//  | '(' subExpr=Expr ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  timeCond=TimeCond
		//| priceCond=PriceCond
		//| occCond=OccCond
		//| '(' subExpr=Expr ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//timeCond=TimeCond
		public Assignment getTimeCondAssignment_0() { return cTimeCondAssignment_0; }
		
		//TimeCond
		public RuleCall getTimeCondTimeCondParserRuleCall_0_0() { return cTimeCondTimeCondParserRuleCall_0_0; }
		
		//priceCond=PriceCond
		public Assignment getPriceCondAssignment_1() { return cPriceCondAssignment_1; }
		
		//PriceCond
		public RuleCall getPriceCondPriceCondParserRuleCall_1_0() { return cPriceCondPriceCondParserRuleCall_1_0; }
		
		//occCond=OccCond
		public Assignment getOccCondAssignment_2() { return cOccCondAssignment_2; }
		
		//OccCond
		public RuleCall getOccCondOccCondParserRuleCall_2_0() { return cOccCondOccCondParserRuleCall_2_0; }
		
		//'(' subExpr=Expr ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//subExpr=Expr
		public Assignment getSubExprAssignment_3_1() { return cSubExprAssignment_3_1; }
		
		//Expr
		public RuleCall getSubExprExprParserRuleCall_3_1_0() { return cSubExprExprParserRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
	}
	public class TimeCondElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.TimeCond");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTimeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cTimeAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cTimeTIME_LITTerminalRuleCall_1_0_1_0 = (RuleCall)cTimeAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cBetweenKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cStartAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cStartTIME_LITTerminalRuleCall_1_1_1_0 = (RuleCall)cStartAssignment_1_1_1.eContents().get(0);
		private final Keyword cToKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Assignment cEndAssignment_1_1_3 = (Assignment)cGroup_1_1.eContents().get(3);
		private final RuleCall cEndTIME_LITTerminalRuleCall_1_1_3_0 = (RuleCall)cEndAssignment_1_1_3.eContents().get(0);
		
		//TimeCond:
		//  'time' ( '=' time=TIME_LIT | 'between' start=TIME_LIT 'to' end=TIME_LIT )
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'time' ( '=' time=TIME_LIT | 'between' start=TIME_LIT 'to' end=TIME_LIT )
		public Group getGroup() { return cGroup; }
		
		//'time'
		public Keyword getTimeKeyword_0() { return cTimeKeyword_0; }
		
		//( '=' time=TIME_LIT | 'between' start=TIME_LIT 'to' end=TIME_LIT )
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'=' time=TIME_LIT
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_0_0() { return cEqualsSignKeyword_1_0_0; }
		
		//time=TIME_LIT
		public Assignment getTimeAssignment_1_0_1() { return cTimeAssignment_1_0_1; }
		
		//TIME_LIT
		public RuleCall getTimeTIME_LITTerminalRuleCall_1_0_1_0() { return cTimeTIME_LITTerminalRuleCall_1_0_1_0; }
		
		//'between' start=TIME_LIT 'to' end=TIME_LIT
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'between'
		public Keyword getBetweenKeyword_1_1_0() { return cBetweenKeyword_1_1_0; }
		
		//start=TIME_LIT
		public Assignment getStartAssignment_1_1_1() { return cStartAssignment_1_1_1; }
		
		//TIME_LIT
		public RuleCall getStartTIME_LITTerminalRuleCall_1_1_1_0() { return cStartTIME_LITTerminalRuleCall_1_1_1_0; }
		
		//'to'
		public Keyword getToKeyword_1_1_2() { return cToKeyword_1_1_2; }
		
		//end=TIME_LIT
		public Assignment getEndAssignment_1_1_3() { return cEndAssignment_1_1_3; }
		
		//TIME_LIT
		public RuleCall getEndTIME_LITTerminalRuleCall_1_1_3_0() { return cEndTIME_LITTerminalRuleCall_1_1_3_0; }
	}
	public class PriceCondElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.PriceCond");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPriceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOpRelOpParserRuleCall_1_0 = (RuleCall)cOpAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueNUMBERTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//PriceCond:
		//  'price' op=RelOp value=NUMBER
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'price' op=RelOp value=NUMBER
		public Group getGroup() { return cGroup; }
		
		//'price'
		public Keyword getPriceKeyword_0() { return cPriceKeyword_0; }
		
		//op=RelOp
		public Assignment getOpAssignment_1() { return cOpAssignment_1; }
		
		//RelOp
		public RuleCall getOpRelOpParserRuleCall_1_0() { return cOpRelOpParserRuleCall_1_0; }
		
		//value=NUMBER
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//NUMBER
		public RuleCall getValueNUMBERTerminalRuleCall_2_0() { return cValueNUMBERTerminalRuleCall_2_0; }
	}
	public class OccCondElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.OccCond");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOccupancyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOpRelOpParserRuleCall_1_0 = (RuleCall)cOpAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//OccCond:
		//  'occupancy' op=RelOp value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'occupancy' op=RelOp value=INT
		public Group getGroup() { return cGroup; }
		
		//'occupancy'
		public Keyword getOccupancyKeyword_0() { return cOccupancyKeyword_0; }
		
		//op=RelOp
		public Assignment getOpAssignment_1() { return cOpAssignment_1; }
		
		//RelOp
		public RuleCall getOpRelOpParserRuleCall_1_0() { return cOpRelOpParserRuleCall_1_0; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}
	public class RelOpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.RelOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cGreaterThanSignEqualsSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLessThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cEqualsSignEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cExclamationMarkEqualsSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//RelOp:
		//  '>' | '<' | '>=' | '<=' | '==' | '!='
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'>' | '<' | '>=' | '<=' | '==' | '!='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_0() { return cGreaterThanSignKeyword_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_2() { return cGreaterThanSignEqualsSignKeyword_2; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_3() { return cLessThanSignEqualsSignKeyword_3; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_4() { return cEqualsSignEqualsSignKeyword_4; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_5() { return cExclamationMarkEqualsSignKeyword_5; }
	}
	
	public class ApplianceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.ApplianceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHVACEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHVACHVACKeyword_0_0 = (Keyword)cHVACEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWaterHeaterEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWaterHeaterWaterHeaterKeyword_1_0 = (Keyword)cWaterHeaterEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWasherEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWasherWasherKeyword_2_0 = (Keyword)cWasherEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDryerEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDryerDryerKeyword_3_0 = (Keyword)cDryerEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLightEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLightLightKeyword_4_0 = (Keyword)cLightEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum ApplianceType:
		//    HVAC='HVAC'
		//  | WaterHeater='WaterHeater'
		//  | Washer='Washer'
		//  | Dryer='Dryer'
		//  | Light='Light'
		//;
		public EnumRule getRule() { return rule; }
		
		//  HVAC='HVAC'
		//| WaterHeater='WaterHeater'
		//| Washer='Washer'
		//| Dryer='Dryer'
		//| Light='Light'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//HVAC='HVAC'
		public EnumLiteralDeclaration getHVACEnumLiteralDeclaration_0() { return cHVACEnumLiteralDeclaration_0; }
		
		//'HVAC'
		public Keyword getHVACHVACKeyword_0_0() { return cHVACHVACKeyword_0_0; }
		
		//WaterHeater='WaterHeater'
		public EnumLiteralDeclaration getWaterHeaterEnumLiteralDeclaration_1() { return cWaterHeaterEnumLiteralDeclaration_1; }
		
		//'WaterHeater'
		public Keyword getWaterHeaterWaterHeaterKeyword_1_0() { return cWaterHeaterWaterHeaterKeyword_1_0; }
		
		//Washer='Washer'
		public EnumLiteralDeclaration getWasherEnumLiteralDeclaration_2() { return cWasherEnumLiteralDeclaration_2; }
		
		//'Washer'
		public Keyword getWasherWasherKeyword_2_0() { return cWasherWasherKeyword_2_0; }
		
		//Dryer='Dryer'
		public EnumLiteralDeclaration getDryerEnumLiteralDeclaration_3() { return cDryerEnumLiteralDeclaration_3; }
		
		//'Dryer'
		public Keyword getDryerDryerKeyword_3_0() { return cDryerDryerKeyword_3_0; }
		
		//Light='Light'
		public EnumLiteralDeclaration getLightEnumLiteralDeclaration_4() { return cLightEnumLiteralDeclaration_4; }
		
		//'Light'
		public Keyword getLightLightKeyword_4_0() { return cLightLightKeyword_4_0; }
	}
	
	private final ModelElements pModel;
	private final ElementElements pElement;
	private final DeclarationElements pDeclaration;
	private final ApplianceTypeElements eApplianceType;
	private final RuleElements pRule;
	private final ActionElements pAction;
	private final TurnActionElements pTurnAction;
	private final SetActionElements pSetAction;
	private final ExprElements pExpr;
	private final OrExprElements pOrExpr;
	private final AndExprElements pAndExpr;
	private final PrimElements pPrim;
	private final TimeCondElements pTimeCond;
	private final PriceCondElements pPriceCond;
	private final OccCondElements pOccCond;
	private final RelOpElements pRelOp;
	private final TerminalRule tTIME_LIT;
	private final TerminalRule tNUMBER;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public HemDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pElement = new ElementElements();
		this.pDeclaration = new DeclarationElements();
		this.eApplianceType = new ApplianceTypeElements();
		this.pRule = new RuleElements();
		this.pAction = new ActionElements();
		this.pTurnAction = new TurnActionElements();
		this.pSetAction = new SetActionElements();
		this.pExpr = new ExprElements();
		this.pOrExpr = new OrExprElements();
		this.pAndExpr = new AndExprElements();
		this.pPrim = new PrimElements();
		this.pTimeCond = new TimeCondElements();
		this.pPriceCond = new PriceCondElements();
		this.pOccCond = new OccCondElements();
		this.pRelOp = new RelOpElements();
		this.tTIME_LIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.TIME_LIT");
		this.tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.homeenergy.HemDsl.NUMBER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.homeenergy.HemDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//  elements+=Element*
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Element:
	//    Declaration
	//  | Rule
	//;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Declaration:
	//  'appliance' name=ID ':' type=ApplianceType ';'
	//;
	public DeclarationElements getDeclarationAccess() {
		return pDeclaration;
	}
	
	public ParserRule getDeclarationRule() {
		return getDeclarationAccess().getRule();
	}
	
	//enum ApplianceType:
	//    HVAC='HVAC'
	//  | WaterHeater='WaterHeater'
	//  | Washer='Washer'
	//  | Dryer='Dryer'
	//  | Light='Light'
	//;
	public ApplianceTypeElements getApplianceTypeAccess() {
		return eApplianceType;
	}
	
	public EnumRule getApplianceTypeRule() {
		return getApplianceTypeAccess().getRule();
	}
	
	//Rule:
	//  'rule' name=ID
	//  'when' condition=Expr
	//  'then' thenAction=Action
	//  ('else' elseAction=Action)?
	//  ';'
	//;
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//Action:
	//    TurnAction
	//  | SetAction
	//;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//TurnAction:
	//  'turn' appliance=[Declaration] action=('on'|'off')
	//;
	public TurnActionElements getTurnActionAccess() {
		return pTurnAction;
	}
	
	public ParserRule getTurnActionRule() {
		return getTurnActionAccess().getRule();
	}
	
	//SetAction:
	//  'set' appliance=[Declaration] 'to' value=NUMBER
	//;
	public SetActionElements getSetActionAccess() {
		return pSetAction;
	}
	
	public ParserRule getSetActionRule() {
		return getSetActionAccess().getRule();
	}
	
	//Expr:
	//  orExpr=OrExpr
	//;
	public ExprElements getExprAccess() {
		return pExpr;
	}
	
	public ParserRule getExprRule() {
		return getExprAccess().getRule();
	}
	
	//OrExpr:
	//  left=AndExpr ( 'or' right+=AndExpr )*
	//;
	public OrExprElements getOrExprAccess() {
		return pOrExpr;
	}
	
	public ParserRule getOrExprRule() {
		return getOrExprAccess().getRule();
	}
	
	//AndExpr:
	//  left=Prim ( 'and' right+=Prim )*
	//;
	public AndExprElements getAndExprAccess() {
		return pAndExpr;
	}
	
	public ParserRule getAndExprRule() {
		return getAndExprAccess().getRule();
	}
	
	//Prim:
	//    timeCond=TimeCond
	//  | priceCond=PriceCond
	//  | occCond=OccCond
	//  | '(' subExpr=Expr ')'
	//;
	public PrimElements getPrimAccess() {
		return pPrim;
	}
	
	public ParserRule getPrimRule() {
		return getPrimAccess().getRule();
	}
	
	//TimeCond:
	//  'time' ( '=' time=TIME_LIT | 'between' start=TIME_LIT 'to' end=TIME_LIT )
	//;
	public TimeCondElements getTimeCondAccess() {
		return pTimeCond;
	}
	
	public ParserRule getTimeCondRule() {
		return getTimeCondAccess().getRule();
	}
	
	//PriceCond:
	//  'price' op=RelOp value=NUMBER
	//;
	public PriceCondElements getPriceCondAccess() {
		return pPriceCond;
	}
	
	public ParserRule getPriceCondRule() {
		return getPriceCondAccess().getRule();
	}
	
	//OccCond:
	//  'occupancy' op=RelOp value=INT
	//;
	public OccCondElements getOccCondAccess() {
		return pOccCond;
	}
	
	public ParserRule getOccCondRule() {
		return getOccCondAccess().getRule();
	}
	
	//RelOp:
	//  '>' | '<' | '>=' | '<=' | '==' | '!='
	//;
	public RelOpElements getRelOpAccess() {
		return pRelOp;
	}
	
	public ParserRule getRelOpRule() {
		return getRelOpAccess().getRule();
	}
	
	////―――――――――――――――――――――――――――
	//// Terminals
	////―――――――――――――――――――――――――――
	//terminal TIME_LIT: INT ':' INT;
	public TerminalRule getTIME_LITRule() {
		return tTIME_LIT;
	}
	
	//terminal NUMBER  : INT ('.' INT)?;
	public TerminalRule getNUMBERRule() {
		return tNUMBER;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
