/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.homeenergy.hemDsl.Expr;
import org.homeenergy.hemDsl.HemDslPackage;
import org.homeenergy.hemDsl.OrExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.impl.ExprImpl#getOrExpr <em>Or Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprImpl extends MinimalEObjectImpl.Container implements Expr
{
  /**
   * The cached value of the '{@link #getOrExpr() <em>Or Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrExpr()
   * @generated
   * @ordered
   */
  protected OrExpr orExpr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HemDslPackage.Literals.EXPR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OrExpr getOrExpr()
  {
    return orExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOrExpr(OrExpr newOrExpr, NotificationChain msgs)
  {
    OrExpr oldOrExpr = orExpr;
    orExpr = newOrExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.EXPR__OR_EXPR, oldOrExpr, newOrExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOrExpr(OrExpr newOrExpr)
  {
    if (newOrExpr != orExpr)
    {
      NotificationChain msgs = null;
      if (orExpr != null)
        msgs = ((InternalEObject)orExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.EXPR__OR_EXPR, null, msgs);
      if (newOrExpr != null)
        msgs = ((InternalEObject)newOrExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.EXPR__OR_EXPR, null, msgs);
      msgs = basicSetOrExpr(newOrExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.EXPR__OR_EXPR, newOrExpr, newOrExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HemDslPackage.EXPR__OR_EXPR:
        return basicSetOrExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HemDslPackage.EXPR__OR_EXPR:
        return getOrExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HemDslPackage.EXPR__OR_EXPR:
        setOrExpr((OrExpr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.EXPR__OR_EXPR:
        setOrExpr((OrExpr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.EXPR__OR_EXPR:
        return orExpr != null;
    }
    return super.eIsSet(featureID);
  }

} //ExprImpl
