/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.homeenergy.hemDsl.Expr;
import org.homeenergy.hemDsl.HemDslPackage;
import org.homeenergy.hemDsl.OccCond;
import org.homeenergy.hemDsl.PriceCond;
import org.homeenergy.hemDsl.Prim;
import org.homeenergy.hemDsl.TimeCond;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prim</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.impl.PrimImpl#getTimeCond <em>Time Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.impl.PrimImpl#getPriceCond <em>Price Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.impl.PrimImpl#getOccCond <em>Occ Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.impl.PrimImpl#getSubExpr <em>Sub Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimImpl extends MinimalEObjectImpl.Container implements Prim
{
  /**
   * The cached value of the '{@link #getTimeCond() <em>Time Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeCond()
   * @generated
   * @ordered
   */
  protected TimeCond timeCond;

  /**
   * The cached value of the '{@link #getPriceCond() <em>Price Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPriceCond()
   * @generated
   * @ordered
   */
  protected PriceCond priceCond;

  /**
   * The cached value of the '{@link #getOccCond() <em>Occ Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOccCond()
   * @generated
   * @ordered
   */
  protected OccCond occCond;

  /**
   * The cached value of the '{@link #getSubExpr() <em>Sub Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubExpr()
   * @generated
   * @ordered
   */
  protected Expr subExpr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HemDslPackage.Literals.PRIM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimeCond getTimeCond()
  {
    return timeCond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTimeCond(TimeCond newTimeCond, NotificationChain msgs)
  {
    TimeCond oldTimeCond = timeCond;
    timeCond = newTimeCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__TIME_COND, oldTimeCond, newTimeCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTimeCond(TimeCond newTimeCond)
  {
    if (newTimeCond != timeCond)
    {
      NotificationChain msgs = null;
      if (timeCond != null)
        msgs = ((InternalEObject)timeCond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__TIME_COND, null, msgs);
      if (newTimeCond != null)
        msgs = ((InternalEObject)newTimeCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__TIME_COND, null, msgs);
      msgs = basicSetTimeCond(newTimeCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__TIME_COND, newTimeCond, newTimeCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PriceCond getPriceCond()
  {
    return priceCond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPriceCond(PriceCond newPriceCond, NotificationChain msgs)
  {
    PriceCond oldPriceCond = priceCond;
    priceCond = newPriceCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__PRICE_COND, oldPriceCond, newPriceCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPriceCond(PriceCond newPriceCond)
  {
    if (newPriceCond != priceCond)
    {
      NotificationChain msgs = null;
      if (priceCond != null)
        msgs = ((InternalEObject)priceCond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__PRICE_COND, null, msgs);
      if (newPriceCond != null)
        msgs = ((InternalEObject)newPriceCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__PRICE_COND, null, msgs);
      msgs = basicSetPriceCond(newPriceCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__PRICE_COND, newPriceCond, newPriceCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OccCond getOccCond()
  {
    return occCond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOccCond(OccCond newOccCond, NotificationChain msgs)
  {
    OccCond oldOccCond = occCond;
    occCond = newOccCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__OCC_COND, oldOccCond, newOccCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOccCond(OccCond newOccCond)
  {
    if (newOccCond != occCond)
    {
      NotificationChain msgs = null;
      if (occCond != null)
        msgs = ((InternalEObject)occCond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__OCC_COND, null, msgs);
      if (newOccCond != null)
        msgs = ((InternalEObject)newOccCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__OCC_COND, null, msgs);
      msgs = basicSetOccCond(newOccCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__OCC_COND, newOccCond, newOccCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expr getSubExpr()
  {
    return subExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubExpr(Expr newSubExpr, NotificationChain msgs)
  {
    Expr oldSubExpr = subExpr;
    subExpr = newSubExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__SUB_EXPR, oldSubExpr, newSubExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubExpr(Expr newSubExpr)
  {
    if (newSubExpr != subExpr)
    {
      NotificationChain msgs = null;
      if (subExpr != null)
        msgs = ((InternalEObject)subExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__SUB_EXPR, null, msgs);
      if (newSubExpr != null)
        msgs = ((InternalEObject)newSubExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.PRIM__SUB_EXPR, null, msgs);
      msgs = basicSetSubExpr(newSubExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.PRIM__SUB_EXPR, newSubExpr, newSubExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HemDslPackage.PRIM__TIME_COND:
        return basicSetTimeCond(null, msgs);
      case HemDslPackage.PRIM__PRICE_COND:
        return basicSetPriceCond(null, msgs);
      case HemDslPackage.PRIM__OCC_COND:
        return basicSetOccCond(null, msgs);
      case HemDslPackage.PRIM__SUB_EXPR:
        return basicSetSubExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HemDslPackage.PRIM__TIME_COND:
        return getTimeCond();
      case HemDslPackage.PRIM__PRICE_COND:
        return getPriceCond();
      case HemDslPackage.PRIM__OCC_COND:
        return getOccCond();
      case HemDslPackage.PRIM__SUB_EXPR:
        return getSubExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HemDslPackage.PRIM__TIME_COND:
        setTimeCond((TimeCond)newValue);
        return;
      case HemDslPackage.PRIM__PRICE_COND:
        setPriceCond((PriceCond)newValue);
        return;
      case HemDslPackage.PRIM__OCC_COND:
        setOccCond((OccCond)newValue);
        return;
      case HemDslPackage.PRIM__SUB_EXPR:
        setSubExpr((Expr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.PRIM__TIME_COND:
        setTimeCond((TimeCond)null);
        return;
      case HemDslPackage.PRIM__PRICE_COND:
        setPriceCond((PriceCond)null);
        return;
      case HemDslPackage.PRIM__OCC_COND:
        setOccCond((OccCond)null);
        return;
      case HemDslPackage.PRIM__SUB_EXPR:
        setSubExpr((Expr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.PRIM__TIME_COND:
        return timeCond != null;
      case HemDslPackage.PRIM__PRICE_COND:
        return priceCond != null;
      case HemDslPackage.PRIM__OCC_COND:
        return occCond != null;
      case HemDslPackage.PRIM__SUB_EXPR:
        return subExpr != null;
    }
    return super.eIsSet(featureID);
  }

} //PrimImpl
