/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.homeenergy.hemDsl.Action;
import org.homeenergy.hemDsl.Expr;
import org.homeenergy.hemDsl.HemDslPackage;
import org.homeenergy.hemDsl.Rule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.impl.RuleImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.impl.RuleImpl#getThenAction <em>Then Action</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.impl.RuleImpl#getElseAction <em>Else Action</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RuleImpl extends ElementImpl implements Rule
{
  /**
   * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition()
   * @generated
   * @ordered
   */
  protected Expr condition;

  /**
   * The cached value of the '{@link #getThenAction() <em>Then Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenAction()
   * @generated
   * @ordered
   */
  protected Action thenAction;

  /**
   * The cached value of the '{@link #getElseAction() <em>Else Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElseAction()
   * @generated
   * @ordered
   */
  protected Action elseAction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HemDslPackage.Literals.RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expr getCondition()
  {
    return condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCondition(Expr newCondition, NotificationChain msgs)
  {
    Expr oldCondition = condition;
    condition = newCondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__CONDITION, oldCondition, newCondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition(Expr newCondition)
  {
    if (newCondition != condition)
    {
      NotificationChain msgs = null;
      if (condition != null)
        msgs = ((InternalEObject)condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__CONDITION, null, msgs);
      if (newCondition != null)
        msgs = ((InternalEObject)newCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__CONDITION, null, msgs);
      msgs = basicSetCondition(newCondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__CONDITION, newCondition, newCondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action getThenAction()
  {
    return thenAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThenAction(Action newThenAction, NotificationChain msgs)
  {
    Action oldThenAction = thenAction;
    thenAction = newThenAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__THEN_ACTION, oldThenAction, newThenAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThenAction(Action newThenAction)
  {
    if (newThenAction != thenAction)
    {
      NotificationChain msgs = null;
      if (thenAction != null)
        msgs = ((InternalEObject)thenAction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__THEN_ACTION, null, msgs);
      if (newThenAction != null)
        msgs = ((InternalEObject)newThenAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__THEN_ACTION, null, msgs);
      msgs = basicSetThenAction(newThenAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__THEN_ACTION, newThenAction, newThenAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action getElseAction()
  {
    return elseAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElseAction(Action newElseAction, NotificationChain msgs)
  {
    Action oldElseAction = elseAction;
    elseAction = newElseAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__ELSE_ACTION, oldElseAction, newElseAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setElseAction(Action newElseAction)
  {
    if (newElseAction != elseAction)
    {
      NotificationChain msgs = null;
      if (elseAction != null)
        msgs = ((InternalEObject)elseAction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__ELSE_ACTION, null, msgs);
      if (newElseAction != null)
        msgs = ((InternalEObject)newElseAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HemDslPackage.RULE__ELSE_ACTION, null, msgs);
      msgs = basicSetElseAction(newElseAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HemDslPackage.RULE__ELSE_ACTION, newElseAction, newElseAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HemDslPackage.RULE__CONDITION:
        return basicSetCondition(null, msgs);
      case HemDslPackage.RULE__THEN_ACTION:
        return basicSetThenAction(null, msgs);
      case HemDslPackage.RULE__ELSE_ACTION:
        return basicSetElseAction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HemDslPackage.RULE__CONDITION:
        return getCondition();
      case HemDslPackage.RULE__THEN_ACTION:
        return getThenAction();
      case HemDslPackage.RULE__ELSE_ACTION:
        return getElseAction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HemDslPackage.RULE__CONDITION:
        setCondition((Expr)newValue);
        return;
      case HemDslPackage.RULE__THEN_ACTION:
        setThenAction((Action)newValue);
        return;
      case HemDslPackage.RULE__ELSE_ACTION:
        setElseAction((Action)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.RULE__CONDITION:
        setCondition((Expr)null);
        return;
      case HemDslPackage.RULE__THEN_ACTION:
        setThenAction((Action)null);
        return;
      case HemDslPackage.RULE__ELSE_ACTION:
        setElseAction((Action)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HemDslPackage.RULE__CONDITION:
        return condition != null;
      case HemDslPackage.RULE__THEN_ACTION:
        return thenAction != null;
      case HemDslPackage.RULE__ELSE_ACTION:
        return elseAction != null;
    }
    return super.eIsSet(featureID);
  }

} //RuleImpl
