/*
 * generated by Xtext 2.38.0
 */
grammar InternalHemDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.homeenergy.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.homeenergy.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.homeenergy.services.HemDslGrammarAccess;

}

@parser::members {

 	private HemDslGrammarAccess grammarAccess;

    public InternalHemDslParser(TokenStream input, HemDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected HemDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getModelAccess().getElementsElementParserRuleCall_0());
			}
			lv_elements_0_0=ruleElement
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getModelRule());
				}
				add(
					$current,
					"elements",
					lv_elements_0_0,
					"org.homeenergy.HemDsl.Element");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleElement
entryRuleElement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getElementRule()); }
	iv_ruleElement=ruleElement
	{ $current=$iv_ruleElement.current; }
	EOF;

// Rule Element
ruleElement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getElementAccess().getDeclarationParserRuleCall_0());
		}
		this_Declaration_0=ruleDeclaration
		{
			$current = $this_Declaration_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getElementAccess().getRuleParserRuleCall_1());
		}
		this_Rule_1=ruleRule
		{
			$current = $this_Rule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleDeclaration
entryRuleDeclaration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDeclarationRule()); }
	iv_ruleDeclaration=ruleDeclaration
	{ $current=$iv_ruleDeclaration.current; }
	EOF;

// Rule Declaration
ruleDeclaration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='appliance'
		{
			newLeafNode(otherlv_0, grammarAccess.getDeclarationAccess().getApplianceKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getDeclarationAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDeclarationRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getDeclarationAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDeclarationAccess().getTypeApplianceTypeEnumRuleCall_3_0());
				}
				lv_type_3_0=ruleApplianceType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDeclarationRule());
					}
					set(
						$current,
						"type",
						lv_type_3_0,
						"org.homeenergy.HemDsl.ApplianceType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4=';'
		{
			newLeafNode(otherlv_4, grammarAccess.getDeclarationAccess().getSemicolonKeyword_4());
		}
	)
;

// Entry rule entryRuleRule
entryRuleRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleRule()); }
	iv_ruleRule=ruleRule
	{ $current=$iv_ruleRule.current; }
	EOF;

// Rule Rule
ruleRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='rule'
		{
			newLeafNode(otherlv_0, grammarAccess.getRuleAccess().getRuleKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getRuleAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRuleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='when'
		{
			newLeafNode(otherlv_2, grammarAccess.getRuleAccess().getWhenKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRuleAccess().getConditionExprParserRuleCall_3_0());
				}
				lv_condition_3_0=ruleExpr
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRuleRule());
					}
					set(
						$current,
						"condition",
						lv_condition_3_0,
						"org.homeenergy.HemDsl.Expr");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='then'
		{
			newLeafNode(otherlv_4, grammarAccess.getRuleAccess().getThenKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRuleAccess().getThenActionActionParserRuleCall_5_0());
				}
				lv_thenAction_5_0=ruleAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRuleRule());
					}
					set(
						$current,
						"thenAction",
						lv_thenAction_5_0,
						"org.homeenergy.HemDsl.Action");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_6='else'
			{
				newLeafNode(otherlv_6, grammarAccess.getRuleAccess().getElseKeyword_6_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRuleAccess().getElseActionActionParserRuleCall_6_1_0());
					}
					lv_elseAction_7_0=ruleAction
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRuleRule());
						}
						set(
							$current,
							"elseAction",
							lv_elseAction_7_0,
							"org.homeenergy.HemDsl.Action");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_8=';'
		{
			newLeafNode(otherlv_8, grammarAccess.getRuleAccess().getSemicolonKeyword_7());
		}
	)
;

// Entry rule entryRuleAction
entryRuleAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getActionRule()); }
	iv_ruleAction=ruleAction
	{ $current=$iv_ruleAction.current; }
	EOF;

// Rule Action
ruleAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getActionAccess().getTurnActionParserRuleCall_0());
		}
		this_TurnAction_0=ruleTurnAction
		{
			$current = $this_TurnAction_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getActionAccess().getSetActionParserRuleCall_1());
		}
		this_SetAction_1=ruleSetAction
		{
			$current = $this_SetAction_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleTurnAction
entryRuleTurnAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTurnActionRule()); }
	iv_ruleTurnAction=ruleTurnAction
	{ $current=$iv_ruleTurnAction.current; }
	EOF;

// Rule TurnAction
ruleTurnAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='turn'
		{
			newLeafNode(otherlv_0, grammarAccess.getTurnActionAccess().getTurnKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTurnActionRule());
					}
				}
				otherlv_1=RULE_ID
				{
					newLeafNode(otherlv_1, grammarAccess.getTurnActionAccess().getApplianceDeclarationCrossReference_1_0());
				}
			)
		)
		(
			(
				(
					lv_action_2_1='on'
					{
						newLeafNode(lv_action_2_1, grammarAccess.getTurnActionAccess().getActionOnKeyword_2_0_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTurnActionRule());
						}
						setWithLastConsumed($current, "action", lv_action_2_1, null);
					}
					    |
					lv_action_2_2='off'
					{
						newLeafNode(lv_action_2_2, grammarAccess.getTurnActionAccess().getActionOffKeyword_2_0_1());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTurnActionRule());
						}
						setWithLastConsumed($current, "action", lv_action_2_2, null);
					}
				)
			)
		)
	)
;

// Entry rule entryRuleSetAction
entryRuleSetAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSetActionRule()); }
	iv_ruleSetAction=ruleSetAction
	{ $current=$iv_ruleSetAction.current; }
	EOF;

// Rule SetAction
ruleSetAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='set'
		{
			newLeafNode(otherlv_0, grammarAccess.getSetActionAccess().getSetKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSetActionRule());
					}
				}
				otherlv_1=RULE_ID
				{
					newLeafNode(otherlv_1, grammarAccess.getSetActionAccess().getApplianceDeclarationCrossReference_1_0());
				}
			)
		)
		otherlv_2='to'
		{
			newLeafNode(otherlv_2, grammarAccess.getSetActionAccess().getToKeyword_2());
		}
		(
			(
				lv_value_3_0=RULE_NUMBER
				{
					newLeafNode(lv_value_3_0, grammarAccess.getSetActionAccess().getValueNUMBERTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSetActionRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_3_0,
						"org.homeenergy.HemDsl.NUMBER");
				}
			)
		)
	)
;

// Entry rule entryRuleExpr
entryRuleExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getExprRule()); }
	iv_ruleExpr=ruleExpr
	{ $current=$iv_ruleExpr.current; }
	EOF;

// Rule Expr
ruleExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getExprAccess().getOrExprOrExprParserRuleCall_0());
			}
			lv_orExpr_0_0=ruleOrExpr
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getExprRule());
				}
				set(
					$current,
					"orExpr",
					lv_orExpr_0_0,
					"org.homeenergy.HemDsl.OrExpr");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleOrExpr
entryRuleOrExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOrExprRule()); }
	iv_ruleOrExpr=ruleOrExpr
	{ $current=$iv_ruleOrExpr.current; }
	EOF;

// Rule OrExpr
ruleOrExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getOrExprAccess().getLeftAndExprParserRuleCall_0_0());
				}
				lv_left_0_0=ruleAndExpr
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOrExprRule());
					}
					set(
						$current,
						"left",
						lv_left_0_0,
						"org.homeenergy.HemDsl.AndExpr");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='or'
			{
				newLeafNode(otherlv_1, grammarAccess.getOrExprAccess().getOrKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getOrExprAccess().getRightAndExprParserRuleCall_1_1_0());
					}
					lv_right_2_0=ruleAndExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOrExprRule());
						}
						add(
							$current,
							"right",
							lv_right_2_0,
							"org.homeenergy.HemDsl.AndExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleAndExpr
entryRuleAndExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAndExprRule()); }
	iv_ruleAndExpr=ruleAndExpr
	{ $current=$iv_ruleAndExpr.current; }
	EOF;

// Rule AndExpr
ruleAndExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAndExprAccess().getLeftPrimParserRuleCall_0_0());
				}
				lv_left_0_0=rulePrim
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAndExprRule());
					}
					set(
						$current,
						"left",
						lv_left_0_0,
						"org.homeenergy.HemDsl.Prim");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='and'
			{
				newLeafNode(otherlv_1, grammarAccess.getAndExprAccess().getAndKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAndExprAccess().getRightPrimParserRuleCall_1_1_0());
					}
					lv_right_2_0=rulePrim
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAndExprRule());
						}
						add(
							$current,
							"right",
							lv_right_2_0,
							"org.homeenergy.HemDsl.Prim");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRulePrim
entryRulePrim returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPrimRule()); }
	iv_rulePrim=rulePrim
	{ $current=$iv_rulePrim.current; }
	EOF;

// Rule Prim
rulePrim returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getPrimAccess().getTimeCondTimeCondParserRuleCall_0_0());
				}
				lv_timeCond_0_0=ruleTimeCond
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPrimRule());
					}
					set(
						$current,
						"timeCond",
						lv_timeCond_0_0,
						"org.homeenergy.HemDsl.TimeCond");
					afterParserOrEnumRuleCall();
				}
			)
		)
		    |
		(
			(
				{
					newCompositeNode(grammarAccess.getPrimAccess().getPriceCondPriceCondParserRuleCall_1_0());
				}
				lv_priceCond_1_0=rulePriceCond
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPrimRule());
					}
					set(
						$current,
						"priceCond",
						lv_priceCond_1_0,
						"org.homeenergy.HemDsl.PriceCond");
					afterParserOrEnumRuleCall();
				}
			)
		)
		    |
		(
			(
				{
					newCompositeNode(grammarAccess.getPrimAccess().getOccCondOccCondParserRuleCall_2_0());
				}
				lv_occCond_2_0=ruleOccCond
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPrimRule());
					}
					set(
						$current,
						"occCond",
						lv_occCond_2_0,
						"org.homeenergy.HemDsl.OccCond");
					afterParserOrEnumRuleCall();
				}
			)
		)
		    |
		(
			otherlv_3='('
			{
				newLeafNode(otherlv_3, grammarAccess.getPrimAccess().getLeftParenthesisKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPrimAccess().getSubExprExprParserRuleCall_3_1_0());
					}
					lv_subExpr_4_0=ruleExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPrimRule());
						}
						set(
							$current,
							"subExpr",
							lv_subExpr_4_0,
							"org.homeenergy.HemDsl.Expr");
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_5=')'
			{
				newLeafNode(otherlv_5, grammarAccess.getPrimAccess().getRightParenthesisKeyword_3_2());
			}
		)
	)
;

// Entry rule entryRuleTimeCond
entryRuleTimeCond returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTimeCondRule()); }
	iv_ruleTimeCond=ruleTimeCond
	{ $current=$iv_ruleTimeCond.current; }
	EOF;

// Rule TimeCond
ruleTimeCond returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='time'
		{
			newLeafNode(otherlv_0, grammarAccess.getTimeCondAccess().getTimeKeyword_0());
		}
		(
			(
				otherlv_1='='
				{
					newLeafNode(otherlv_1, grammarAccess.getTimeCondAccess().getEqualsSignKeyword_1_0_0());
				}
				(
					(
						lv_time_2_0=RULE_TIME_LIT
						{
							newLeafNode(lv_time_2_0, grammarAccess.getTimeCondAccess().getTimeTIME_LITTerminalRuleCall_1_0_1_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getTimeCondRule());
							}
							setWithLastConsumed(
								$current,
								"time",
								lv_time_2_0,
								"org.homeenergy.HemDsl.TIME_LIT");
						}
					)
				)
			)
			    |
			(
				otherlv_3='between'
				{
					newLeafNode(otherlv_3, grammarAccess.getTimeCondAccess().getBetweenKeyword_1_1_0());
				}
				(
					(
						lv_start_4_0=RULE_TIME_LIT
						{
							newLeafNode(lv_start_4_0, grammarAccess.getTimeCondAccess().getStartTIME_LITTerminalRuleCall_1_1_1_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getTimeCondRule());
							}
							setWithLastConsumed(
								$current,
								"start",
								lv_start_4_0,
								"org.homeenergy.HemDsl.TIME_LIT");
						}
					)
				)
				otherlv_5='to'
				{
					newLeafNode(otherlv_5, grammarAccess.getTimeCondAccess().getToKeyword_1_1_2());
				}
				(
					(
						lv_end_6_0=RULE_TIME_LIT
						{
							newLeafNode(lv_end_6_0, grammarAccess.getTimeCondAccess().getEndTIME_LITTerminalRuleCall_1_1_3_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getTimeCondRule());
							}
							setWithLastConsumed(
								$current,
								"end",
								lv_end_6_0,
								"org.homeenergy.HemDsl.TIME_LIT");
						}
					)
				)
			)
		)
	)
;

// Entry rule entryRulePriceCond
entryRulePriceCond returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPriceCondRule()); }
	iv_rulePriceCond=rulePriceCond
	{ $current=$iv_rulePriceCond.current; }
	EOF;

// Rule PriceCond
rulePriceCond returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='price'
		{
			newLeafNode(otherlv_0, grammarAccess.getPriceCondAccess().getPriceKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPriceCondAccess().getOpRelOpParserRuleCall_1_0());
				}
				lv_op_1_0=ruleRelOp
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPriceCondRule());
					}
					set(
						$current,
						"op",
						lv_op_1_0,
						"org.homeenergy.HemDsl.RelOp");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_value_2_0=RULE_NUMBER
				{
					newLeafNode(lv_value_2_0, grammarAccess.getPriceCondAccess().getValueNUMBERTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPriceCondRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_2_0,
						"org.homeenergy.HemDsl.NUMBER");
				}
			)
		)
	)
;

// Entry rule entryRuleOccCond
entryRuleOccCond returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOccCondRule()); }
	iv_ruleOccCond=ruleOccCond
	{ $current=$iv_ruleOccCond.current; }
	EOF;

// Rule OccCond
ruleOccCond returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='occupancy'
		{
			newLeafNode(otherlv_0, grammarAccess.getOccCondAccess().getOccupancyKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getOccCondAccess().getOpRelOpParserRuleCall_1_0());
				}
				lv_op_1_0=ruleRelOp
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOccCondRule());
					}
					set(
						$current,
						"op",
						lv_op_1_0,
						"org.homeenergy.HemDsl.RelOp");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_value_2_0=RULE_INT
				{
					newLeafNode(lv_value_2_0, grammarAccess.getOccCondAccess().getValueINTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOccCondRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleRelOp
entryRuleRelOp returns [String current=null]:
	{ newCompositeNode(grammarAccess.getRelOpRule()); }
	iv_ruleRelOp=ruleRelOp
	{ $current=$iv_ruleRelOp.current.getText(); }
	EOF;

// Rule RelOp
ruleRelOp returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='>'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getGreaterThanSignKeyword_0());
		}
		    |
		kw='<'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getLessThanSignKeyword_1());
		}
		    |
		kw='>='
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getGreaterThanSignEqualsSignKeyword_2());
		}
		    |
		kw='<='
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getLessThanSignEqualsSignKeyword_3());
		}
		    |
		kw='=='
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getEqualsSignEqualsSignKeyword_4());
		}
		    |
		kw='!='
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getRelOpAccess().getExclamationMarkEqualsSignKeyword_5());
		}
	)
;

// Rule ApplianceType
ruleApplianceType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='HVAC'
			{
				$current = grammarAccess.getApplianceTypeAccess().getHVACEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getApplianceTypeAccess().getHVACEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='WaterHeater'
			{
				$current = grammarAccess.getApplianceTypeAccess().getWaterHeaterEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getApplianceTypeAccess().getWaterHeaterEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='Washer'
			{
				$current = grammarAccess.getApplianceTypeAccess().getWasherEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getApplianceTypeAccess().getWasherEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='Dryer'
			{
				$current = grammarAccess.getApplianceTypeAccess().getDryerEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getApplianceTypeAccess().getDryerEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='Light'
			{
				$current = grammarAccess.getApplianceTypeAccess().getLightEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getApplianceTypeAccess().getLightEnumLiteralDeclaration_4());
			}
		)
	)
;

RULE_TIME_LIT : RULE_INT ':' RULE_INT;

RULE_NUMBER : RULE_INT ('.' RULE_INT)?;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
