/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.Action#getAppliance <em>Appliance</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Appliance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Appliance</em>' reference.
   * @see #setAppliance(Declaration)
   * @see org.homeenergy.hemDsl.HemDslPackage#getAction_Appliance()
   * @model
   * @generated
   */
  Declaration getAppliance();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Action#getAppliance <em>Appliance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Appliance</em>' reference.
   * @see #getAppliance()
   * @generated
   */
  void setAppliance(Declaration value);

} // Action
