/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Appliance Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.homeenergy.hemDsl.HemDslPackage#getApplianceType()
 * @model
 * @generated
 */
public enum ApplianceType implements Enumerator
{
  /**
   * The '<em><b>HVAC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HVAC_VALUE
   * @generated
   * @ordered
   */
  HVAC(0, "HVAC", "HVAC"),

  /**
   * The '<em><b>Water Heater</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WATER_HEATER_VALUE
   * @generated
   * @ordered
   */
  WATER_HEATER(1, "WaterHeater", "WaterHeater"),

  /**
   * The '<em><b>Washer</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WASHER_VALUE
   * @generated
   * @ordered
   */
  WASHER(2, "Washer", "Washer"),

  /**
   * The '<em><b>Dryer</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRYER_VALUE
   * @generated
   * @ordered
   */
  DRYER(3, "Dryer", "Dryer"),

  /**
   * The '<em><b>Light</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIGHT_VALUE
   * @generated
   * @ordered
   */
  LIGHT(4, "Light", "Light");

  /**
   * The '<em><b>HVAC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HVAC
   * @model
   * @generated
   * @ordered
   */
  public static final int HVAC_VALUE = 0;

  /**
   * The '<em><b>Water Heater</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WATER_HEATER
   * @model name="WaterHeater"
   * @generated
   * @ordered
   */
  public static final int WATER_HEATER_VALUE = 1;

  /**
   * The '<em><b>Washer</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WASHER
   * @model name="Washer"
   * @generated
   * @ordered
   */
  public static final int WASHER_VALUE = 2;

  /**
   * The '<em><b>Dryer</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DRYER
   * @model name="Dryer"
   * @generated
   * @ordered
   */
  public static final int DRYER_VALUE = 3;

  /**
   * The '<em><b>Light</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIGHT
   * @model name="Light"
   * @generated
   * @ordered
   */
  public static final int LIGHT_VALUE = 4;

  /**
   * An array of all the '<em><b>Appliance Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ApplianceType[] VALUES_ARRAY =
    new ApplianceType[]
    {
      HVAC,
      WATER_HEATER,
      WASHER,
      DRYER,
      LIGHT,
    };

  /**
   * A public read-only list of all the '<em><b>Appliance Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ApplianceType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Appliance Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ApplianceType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ApplianceType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Appliance Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ApplianceType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ApplianceType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Appliance Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ApplianceType get(int value)
  {
    switch (value)
    {
      case HVAC_VALUE: return HVAC;
      case WATER_HEATER_VALUE: return WATER_HEATER;
      case WASHER_VALUE: return WASHER;
      case DRYER_VALUE: return DRYER;
      case LIGHT_VALUE: return LIGHT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ApplianceType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ApplianceType
