/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.Declaration#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends Element
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.homeenergy.hemDsl.ApplianceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.homeenergy.hemDsl.ApplianceType
   * @see #setType(ApplianceType)
   * @see org.homeenergy.hemDsl.HemDslPackage#getDeclaration_Type()
   * @model
   * @generated
   */
  ApplianceType getType();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Declaration#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.homeenergy.hemDsl.ApplianceType
   * @see #getType()
   * @generated
   */
  void setType(ApplianceType value);

} // Declaration
