/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.Expr#getOrExpr <em>Or Expr</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Or Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or Expr</em>' containment reference.
   * @see #setOrExpr(OrExpr)
   * @see org.homeenergy.hemDsl.HemDslPackage#getExpr_OrExpr()
   * @model containment="true"
   * @generated
   */
  OrExpr getOrExpr();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Expr#getOrExpr <em>Or Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or Expr</em>' containment reference.
   * @see #getOrExpr()
   * @generated
   */
  void setOrExpr(OrExpr value);

} // Expr
