/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.homeenergy.hemDsl.HemDslFactory
 * @model kind="package"
 * @generated
 */
public interface HemDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hemDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.homeenergy.org/HEMDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hemDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HemDslPackage eINSTANCE = org.homeenergy.hemDsl.impl.HemDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.ModelImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.ElementImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.DeclarationImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TYPE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.RuleImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__THEN_ACTION = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ELSE_ACTION = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.ActionImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 4;

  /**
   * The feature id for the '<em><b>Appliance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__APPLIANCE = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.TurnActionImpl <em>Turn Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.TurnActionImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getTurnAction()
   * @generated
   */
  int TURN_ACTION = 5;

  /**
   * The feature id for the '<em><b>Appliance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_ACTION__APPLIANCE = ACTION__APPLIANCE;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_ACTION__ACTION = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Turn Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.SetActionImpl <em>Set Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.SetActionImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getSetAction()
   * @generated
   */
  int SET_ACTION = 6;

  /**
   * The feature id for the '<em><b>Appliance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ACTION__APPLIANCE = ACTION__APPLIANCE;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ACTION__VALUE = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Set Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.ExprImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 7;

  /**
   * The feature id for the '<em><b>Or Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__OR_EXPR = 0;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.OrExprImpl <em>Or Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.OrExprImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getOrExpr()
   * @generated
   */
  int OR_EXPR = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR__RIGHT = 1;

  /**
   * The number of structural features of the '<em>Or Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.AndExprImpl <em>And Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.AndExprImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getAndExpr()
   * @generated
   */
  int AND_EXPR = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR__RIGHT = 1;

  /**
   * The number of structural features of the '<em>And Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.PrimImpl <em>Prim</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.PrimImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getPrim()
   * @generated
   */
  int PRIM = 10;

  /**
   * The feature id for the '<em><b>Time Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__TIME_COND = 0;

  /**
   * The feature id for the '<em><b>Price Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__PRICE_COND = 1;

  /**
   * The feature id for the '<em><b>Occ Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__OCC_COND = 2;

  /**
   * The feature id for the '<em><b>Sub Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM__SUB_EXPR = 3;

  /**
   * The number of structural features of the '<em>Prim</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.TimeCondImpl <em>Time Cond</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.TimeCondImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getTimeCond()
   * @generated
   */
  int TIME_COND = 11;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_COND__TIME = 0;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_COND__START = 1;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_COND__END = 2;

  /**
   * The number of structural features of the '<em>Time Cond</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_COND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.PriceCondImpl <em>Price Cond</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.PriceCondImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getPriceCond()
   * @generated
   */
  int PRICE_COND = 12;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRICE_COND__OP = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRICE_COND__VALUE = 1;

  /**
   * The number of structural features of the '<em>Price Cond</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRICE_COND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.impl.OccCondImpl <em>Occ Cond</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.impl.OccCondImpl
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getOccCond()
   * @generated
   */
  int OCC_COND = 13;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCC_COND__OP = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCC_COND__VALUE = 1;

  /**
   * The number of structural features of the '<em>Occ Cond</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCC_COND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.homeenergy.hemDsl.ApplianceType <em>Appliance Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.homeenergy.hemDsl.ApplianceType
   * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getApplianceType()
   * @generated
   */
  int APPLIANCE_TYPE = 14;


  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.homeenergy.hemDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.homeenergy.hemDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.homeenergy.hemDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.homeenergy.hemDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.homeenergy.hemDsl.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.homeenergy.hemDsl.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.Declaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.homeenergy.hemDsl.Declaration#getType()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Type();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.homeenergy.hemDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.homeenergy.hemDsl.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Condition();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Rule#getThenAction <em>Then Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Action</em>'.
   * @see org.homeenergy.hemDsl.Rule#getThenAction()
   * @see #getRule()
   * @generated
   */
  EReference getRule_ThenAction();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Rule#getElseAction <em>Else Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Action</em>'.
   * @see org.homeenergy.hemDsl.Rule#getElseAction()
   * @see #getRule()
   * @generated
   */
  EReference getRule_ElseAction();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.homeenergy.hemDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the reference '{@link org.homeenergy.hemDsl.Action#getAppliance <em>Appliance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Appliance</em>'.
   * @see org.homeenergy.hemDsl.Action#getAppliance()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Appliance();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.TurnAction <em>Turn Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Action</em>'.
   * @see org.homeenergy.hemDsl.TurnAction
   * @generated
   */
  EClass getTurnAction();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.TurnAction#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.homeenergy.hemDsl.TurnAction#getAction()
   * @see #getTurnAction()
   * @generated
   */
  EAttribute getTurnAction_Action();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.SetAction <em>Set Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Action</em>'.
   * @see org.homeenergy.hemDsl.SetAction
   * @generated
   */
  EClass getSetAction();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.SetAction#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.homeenergy.hemDsl.SetAction#getValue()
   * @see #getSetAction()
   * @generated
   */
  EAttribute getSetAction_Value();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.homeenergy.hemDsl.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Expr#getOrExpr <em>Or Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Or Expr</em>'.
   * @see org.homeenergy.hemDsl.Expr#getOrExpr()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_OrExpr();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.OrExpr <em>Or Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Expr</em>'.
   * @see org.homeenergy.hemDsl.OrExpr
   * @generated
   */
  EClass getOrExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.OrExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.homeenergy.hemDsl.OrExpr#getLeft()
   * @see #getOrExpr()
   * @generated
   */
  EReference getOrExpr_Left();

  /**
   * Returns the meta object for the containment reference list '{@link org.homeenergy.hemDsl.OrExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see org.homeenergy.hemDsl.OrExpr#getRight()
   * @see #getOrExpr()
   * @generated
   */
  EReference getOrExpr_Right();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.AndExpr <em>And Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expr</em>'.
   * @see org.homeenergy.hemDsl.AndExpr
   * @generated
   */
  EClass getAndExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.AndExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.homeenergy.hemDsl.AndExpr#getLeft()
   * @see #getAndExpr()
   * @generated
   */
  EReference getAndExpr_Left();

  /**
   * Returns the meta object for the containment reference list '{@link org.homeenergy.hemDsl.AndExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see org.homeenergy.hemDsl.AndExpr#getRight()
   * @see #getAndExpr()
   * @generated
   */
  EReference getAndExpr_Right();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.Prim <em>Prim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prim</em>'.
   * @see org.homeenergy.hemDsl.Prim
   * @generated
   */
  EClass getPrim();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Prim#getTimeCond <em>Time Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time Cond</em>'.
   * @see org.homeenergy.hemDsl.Prim#getTimeCond()
   * @see #getPrim()
   * @generated
   */
  EReference getPrim_TimeCond();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Prim#getPriceCond <em>Price Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Price Cond</em>'.
   * @see org.homeenergy.hemDsl.Prim#getPriceCond()
   * @see #getPrim()
   * @generated
   */
  EReference getPrim_PriceCond();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Prim#getOccCond <em>Occ Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Occ Cond</em>'.
   * @see org.homeenergy.hemDsl.Prim#getOccCond()
   * @see #getPrim()
   * @generated
   */
  EReference getPrim_OccCond();

  /**
   * Returns the meta object for the containment reference '{@link org.homeenergy.hemDsl.Prim#getSubExpr <em>Sub Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub Expr</em>'.
   * @see org.homeenergy.hemDsl.Prim#getSubExpr()
   * @see #getPrim()
   * @generated
   */
  EReference getPrim_SubExpr();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.TimeCond <em>Time Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Cond</em>'.
   * @see org.homeenergy.hemDsl.TimeCond
   * @generated
   */
  EClass getTimeCond();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.TimeCond#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.homeenergy.hemDsl.TimeCond#getTime()
   * @see #getTimeCond()
   * @generated
   */
  EAttribute getTimeCond_Time();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.TimeCond#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.homeenergy.hemDsl.TimeCond#getStart()
   * @see #getTimeCond()
   * @generated
   */
  EAttribute getTimeCond_Start();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.TimeCond#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.homeenergy.hemDsl.TimeCond#getEnd()
   * @see #getTimeCond()
   * @generated
   */
  EAttribute getTimeCond_End();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.PriceCond <em>Price Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Price Cond</em>'.
   * @see org.homeenergy.hemDsl.PriceCond
   * @generated
   */
  EClass getPriceCond();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.PriceCond#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.homeenergy.hemDsl.PriceCond#getOp()
   * @see #getPriceCond()
   * @generated
   */
  EAttribute getPriceCond_Op();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.PriceCond#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.homeenergy.hemDsl.PriceCond#getValue()
   * @see #getPriceCond()
   * @generated
   */
  EAttribute getPriceCond_Value();

  /**
   * Returns the meta object for class '{@link org.homeenergy.hemDsl.OccCond <em>Occ Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occ Cond</em>'.
   * @see org.homeenergy.hemDsl.OccCond
   * @generated
   */
  EClass getOccCond();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.OccCond#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.homeenergy.hemDsl.OccCond#getOp()
   * @see #getOccCond()
   * @generated
   */
  EAttribute getOccCond_Op();

  /**
   * Returns the meta object for the attribute '{@link org.homeenergy.hemDsl.OccCond#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.homeenergy.hemDsl.OccCond#getValue()
   * @see #getOccCond()
   * @generated
   */
  EAttribute getOccCond_Value();

  /**
   * Returns the meta object for enum '{@link org.homeenergy.hemDsl.ApplianceType <em>Appliance Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Appliance Type</em>'.
   * @see org.homeenergy.hemDsl.ApplianceType
   * @generated
   */
  EEnum getApplianceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HemDslFactory getHemDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.ModelImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.ElementImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.DeclarationImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__TYPE = eINSTANCE.getDeclaration_Type();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.RuleImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Then Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__THEN_ACTION = eINSTANCE.getRule_ThenAction();

    /**
     * The meta object literal for the '<em><b>Else Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ELSE_ACTION = eINSTANCE.getRule_ElseAction();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.ActionImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Appliance</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__APPLIANCE = eINSTANCE.getAction_Appliance();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.TurnActionImpl <em>Turn Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.TurnActionImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getTurnAction()
     * @generated
     */
    EClass TURN_ACTION = eINSTANCE.getTurnAction();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_ACTION__ACTION = eINSTANCE.getTurnAction_Action();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.SetActionImpl <em>Set Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.SetActionImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getSetAction()
     * @generated
     */
    EClass SET_ACTION = eINSTANCE.getSetAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SET_ACTION__VALUE = eINSTANCE.getSetAction_Value();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.ExprImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Or Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__OR_EXPR = eINSTANCE.getExpr_OrExpr();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.OrExprImpl <em>Or Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.OrExprImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getOrExpr()
     * @generated
     */
    EClass OR_EXPR = eINSTANCE.getOrExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPR__LEFT = eINSTANCE.getOrExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPR__RIGHT = eINSTANCE.getOrExpr_Right();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.AndExprImpl <em>And Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.AndExprImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getAndExpr()
     * @generated
     */
    EClass AND_EXPR = eINSTANCE.getAndExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPR__LEFT = eINSTANCE.getAndExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPR__RIGHT = eINSTANCE.getAndExpr_Right();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.PrimImpl <em>Prim</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.PrimImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getPrim()
     * @generated
     */
    EClass PRIM = eINSTANCE.getPrim();

    /**
     * The meta object literal for the '<em><b>Time Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__TIME_COND = eINSTANCE.getPrim_TimeCond();

    /**
     * The meta object literal for the '<em><b>Price Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__PRICE_COND = eINSTANCE.getPrim_PriceCond();

    /**
     * The meta object literal for the '<em><b>Occ Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__OCC_COND = eINSTANCE.getPrim_OccCond();

    /**
     * The meta object literal for the '<em><b>Sub Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIM__SUB_EXPR = eINSTANCE.getPrim_SubExpr();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.TimeCondImpl <em>Time Cond</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.TimeCondImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getTimeCond()
     * @generated
     */
    EClass TIME_COND = eINSTANCE.getTimeCond();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_COND__TIME = eINSTANCE.getTimeCond_Time();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_COND__START = eINSTANCE.getTimeCond_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_COND__END = eINSTANCE.getTimeCond_End();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.PriceCondImpl <em>Price Cond</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.PriceCondImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getPriceCond()
     * @generated
     */
    EClass PRICE_COND = eINSTANCE.getPriceCond();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRICE_COND__OP = eINSTANCE.getPriceCond_Op();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRICE_COND__VALUE = eINSTANCE.getPriceCond_Value();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.impl.OccCondImpl <em>Occ Cond</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.impl.OccCondImpl
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getOccCond()
     * @generated
     */
    EClass OCC_COND = eINSTANCE.getOccCond();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OCC_COND__OP = eINSTANCE.getOccCond_Op();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OCC_COND__VALUE = eINSTANCE.getOccCond_Value();

    /**
     * The meta object literal for the '{@link org.homeenergy.hemDsl.ApplianceType <em>Appliance Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.homeenergy.hemDsl.ApplianceType
     * @see org.homeenergy.hemDsl.impl.HemDslPackageImpl#getApplianceType()
     * @generated
     */
    EEnum APPLIANCE_TYPE = eINSTANCE.getApplianceType();

  }

} //HemDslPackage
