/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.OrExpr#getLeft <em>Left</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.OrExpr#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getOrExpr()
 * @model
 * @generated
 */
public interface OrExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(AndExpr)
   * @see org.homeenergy.hemDsl.HemDslPackage#getOrExpr_Left()
   * @model containment="true"
   * @generated
   */
  AndExpr getLeft();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.OrExpr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(AndExpr value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link org.homeenergy.hemDsl.AndExpr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see org.homeenergy.hemDsl.HemDslPackage#getOrExpr_Right()
   * @model containment="true"
   * @generated
   */
  EList<AndExpr> getRight();

} // OrExpr
