/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prim</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.Prim#getTimeCond <em>Time Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.Prim#getPriceCond <em>Price Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.Prim#getOccCond <em>Occ Cond</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.Prim#getSubExpr <em>Sub Expr</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getPrim()
 * @model
 * @generated
 */
public interface Prim extends EObject
{
  /**
   * Returns the value of the '<em><b>Time Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Cond</em>' containment reference.
   * @see #setTimeCond(TimeCond)
   * @see org.homeenergy.hemDsl.HemDslPackage#getPrim_TimeCond()
   * @model containment="true"
   * @generated
   */
  TimeCond getTimeCond();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Prim#getTimeCond <em>Time Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Cond</em>' containment reference.
   * @see #getTimeCond()
   * @generated
   */
  void setTimeCond(TimeCond value);

  /**
   * Returns the value of the '<em><b>Price Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price Cond</em>' containment reference.
   * @see #setPriceCond(PriceCond)
   * @see org.homeenergy.hemDsl.HemDslPackage#getPrim_PriceCond()
   * @model containment="true"
   * @generated
   */
  PriceCond getPriceCond();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Prim#getPriceCond <em>Price Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price Cond</em>' containment reference.
   * @see #getPriceCond()
   * @generated
   */
  void setPriceCond(PriceCond value);

  /**
   * Returns the value of the '<em><b>Occ Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occ Cond</em>' containment reference.
   * @see #setOccCond(OccCond)
   * @see org.homeenergy.hemDsl.HemDslPackage#getPrim_OccCond()
   * @model containment="true"
   * @generated
   */
  OccCond getOccCond();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Prim#getOccCond <em>Occ Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occ Cond</em>' containment reference.
   * @see #getOccCond()
   * @generated
   */
  void setOccCond(OccCond value);

  /**
   * Returns the value of the '<em><b>Sub Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Expr</em>' containment reference.
   * @see #setSubExpr(Expr)
   * @see org.homeenergy.hemDsl.HemDslPackage#getPrim_SubExpr()
   * @model containment="true"
   * @generated
   */
  Expr getSubExpr();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Prim#getSubExpr <em>Sub Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Expr</em>' containment reference.
   * @see #getSubExpr()
   * @generated
   */
  void setSubExpr(Expr value);

} // Prim
