/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.Rule#getThenAction <em>Then Action</em>}</li>
 *   <li>{@link org.homeenergy.hemDsl.Rule#getElseAction <em>Else Action</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends Element
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expr)
   * @see org.homeenergy.hemDsl.HemDslPackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Expr getCondition();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expr value);

  /**
   * Returns the value of the '<em><b>Then Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Action</em>' containment reference.
   * @see #setThenAction(Action)
   * @see org.homeenergy.hemDsl.HemDslPackage#getRule_ThenAction()
   * @model containment="true"
   * @generated
   */
  Action getThenAction();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Rule#getThenAction <em>Then Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Action</em>' containment reference.
   * @see #getThenAction()
   * @generated
   */
  void setThenAction(Action value);

  /**
   * Returns the value of the '<em><b>Else Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Action</em>' containment reference.
   * @see #setElseAction(Action)
   * @see org.homeenergy.hemDsl.HemDslPackage#getRule_ElseAction()
   * @model containment="true"
   * @generated
   */
  Action getElseAction();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.Rule#getElseAction <em>Else Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Action</em>' containment reference.
   * @see #getElseAction()
   * @generated
   */
  void setElseAction(Action value);

} // Rule
