/**
 * generated by Xtext 2.38.0
 */
package org.homeenergy.hemDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.homeenergy.hemDsl.TurnAction#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see org.homeenergy.hemDsl.HemDslPackage#getTurnAction()
 * @model
 * @generated
 */
public interface TurnAction extends Action
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see org.homeenergy.hemDsl.HemDslPackage#getTurnAction_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link org.homeenergy.hemDsl.TurnAction#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // TurnAction
