/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHemDslScopeProvider extends DelegatingScopeProvider {
}
