/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HemDslStandaloneSetup extends HemDslStandaloneSetupGenerated {

	public static void doSetup() {
		new HemDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
