/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.homeenergy.HemDslRuntimeModule;
import org.homeenergy.HemDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HemDslIdeSetup extends HemDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HemDslRuntimeModule(), new HemDslIdeModule()));
	}
	
}
