/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.homeenergy.hemDsl.AndExpr;
import org.homeenergy.hemDsl.Declaration;
import org.homeenergy.hemDsl.Expr;
import org.homeenergy.hemDsl.HemDslPackage;
import org.homeenergy.hemDsl.Model;
import org.homeenergy.hemDsl.OccCond;
import org.homeenergy.hemDsl.OrExpr;
import org.homeenergy.hemDsl.PriceCond;
import org.homeenergy.hemDsl.Prim;
import org.homeenergy.hemDsl.Rule;
import org.homeenergy.hemDsl.SetAction;
import org.homeenergy.hemDsl.TimeCond;
import org.homeenergy.hemDsl.TurnAction;
import org.homeenergy.services.HemDslGrammarAccess;

@SuppressWarnings("all")
public class HemDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private HemDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == HemDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case HemDslPackage.AND_EXPR:
				sequence_AndExpr(context, (AndExpr) semanticObject); 
				return; 
			case HemDslPackage.DECLARATION:
				sequence_Declaration(context, (Declaration) semanticObject); 
				return; 
			case HemDslPackage.EXPR:
				sequence_Expr(context, (Expr) semanticObject); 
				return; 
			case HemDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case HemDslPackage.OCC_COND:
				sequence_OccCond(context, (OccCond) semanticObject); 
				return; 
			case HemDslPackage.OR_EXPR:
				sequence_OrExpr(context, (OrExpr) semanticObject); 
				return; 
			case HemDslPackage.PRICE_COND:
				sequence_PriceCond(context, (PriceCond) semanticObject); 
				return; 
			case HemDslPackage.PRIM:
				sequence_Prim(context, (Prim) semanticObject); 
				return; 
			case HemDslPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case HemDslPackage.SET_ACTION:
				sequence_SetAction(context, (SetAction) semanticObject); 
				return; 
			case HemDslPackage.TIME_COND:
				sequence_TimeCond(context, (TimeCond) semanticObject); 
				return; 
			case HemDslPackage.TURN_ACTION:
				sequence_TurnAction(context, (TurnAction) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AndExpr returns AndExpr
	 *
	 * Constraint:
	 *     (left=Prim right+=Prim*)
	 * </pre>
	 */
	protected void sequence_AndExpr(ISerializationContext context, AndExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Element returns Declaration
	 *     Declaration returns Declaration
	 *
	 * Constraint:
	 *     (name=ID type=ApplianceType)
	 * </pre>
	 */
	protected void sequence_Declaration(ISerializationContext context, Declaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.DECLARATION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.DECLARATION__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeclarationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDeclarationAccess().getTypeApplianceTypeEnumRuleCall_3_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Expr
	 *
	 * Constraint:
	 *     orExpr=OrExpr
	 * </pre>
	 */
	protected void sequence_Expr(ISerializationContext context, Expr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.EXPR__OR_EXPR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.EXPR__OR_EXPR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExprAccess().getOrExprOrExprParserRuleCall_0(), semanticObject.getOrExpr());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=Element+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OccCond returns OccCond
	 *
	 * Constraint:
	 *     (op=RelOp value=INT)
	 * </pre>
	 */
	protected void sequence_OccCond(ISerializationContext context, OccCond semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.OCC_COND__OP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.OCC_COND__OP));
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.OCC_COND__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.OCC_COND__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOccCondAccess().getOpRelOpParserRuleCall_1_0(), semanticObject.getOp());
		feeder.accept(grammarAccess.getOccCondAccess().getValueINTTerminalRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OrExpr returns OrExpr
	 *
	 * Constraint:
	 *     (left=AndExpr right+=AndExpr*)
	 * </pre>
	 */
	protected void sequence_OrExpr(ISerializationContext context, OrExpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PriceCond returns PriceCond
	 *
	 * Constraint:
	 *     (op=RelOp value=NUMBER)
	 * </pre>
	 */
	protected void sequence_PriceCond(ISerializationContext context, PriceCond semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.PRICE_COND__OP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.PRICE_COND__OP));
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.PRICE_COND__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.PRICE_COND__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPriceCondAccess().getOpRelOpParserRuleCall_1_0(), semanticObject.getOp());
		feeder.accept(grammarAccess.getPriceCondAccess().getValueNUMBERTerminalRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Prim returns Prim
	 *
	 * Constraint:
	 *     (timeCond=TimeCond | priceCond=PriceCond | occCond=OccCond | subExpr=Expr)
	 * </pre>
	 */
	protected void sequence_Prim(ISerializationContext context, Prim semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Element returns Rule
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (name=ID condition=Expr thenAction=Action elseAction=Action?)
	 * </pre>
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns SetAction
	 *     SetAction returns SetAction
	 *
	 * Constraint:
	 *     (appliance=[Declaration|ID] value=NUMBER)
	 * </pre>
	 */
	protected void sequence_SetAction(ISerializationContext context, SetAction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.ACTION__APPLIANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.ACTION__APPLIANCE));
			if (transientValues.isValueTransient(semanticObject, HemDslPackage.Literals.SET_ACTION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HemDslPackage.Literals.SET_ACTION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSetActionAccess().getApplianceDeclarationIDTerminalRuleCall_1_0_1(), semanticObject.eGet(HemDslPackage.Literals.ACTION__APPLIANCE, false));
		feeder.accept(grammarAccess.getSetActionAccess().getValueNUMBERTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TimeCond returns TimeCond
	 *
	 * Constraint:
	 *     (time=TIME_LIT | (start=TIME_LIT end=TIME_LIT))
	 * </pre>
	 */
	protected void sequence_TimeCond(ISerializationContext context, TimeCond semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns TurnAction
	 *     TurnAction returns TurnAction
	 *
	 * Constraint:
	 *     (appliance=[Declaration|ID] (action='on' | action='off'))
	 * </pre>
	 */
	protected void sequence_TurnAction(ISerializationContext context, TurnAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
