/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.homeenrgy.ui.internal.HomeenrgyActivator;

public class HemDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HomeenrgyActivator.getInstance().getInjector("org.homeenergy.HemDsl");
	}

}
