/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.homeenrgy.ui.internal.HomeenrgyActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HemDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HomeenrgyActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HomeenrgyActivator activator = HomeenrgyActivator.getInstance();
		return activator != null ? activator.getInjector(HomeenrgyActivator.ORG_HOMEENERGY_HEMDSL) : null;
	}

}
