/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.homeenergy.ide.contentassist.antlr.internal.InternalHemDslParser;
import org.homeenergy.services.HemDslGrammarAccess;

public class HemDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(HemDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, HemDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getTurnActionAccess().getActionAlternatives_2_0(), "rule__TurnAction__ActionAlternatives_2_0");
			builder.put(grammarAccess.getPrimAccess().getAlternatives(), "rule__Prim__Alternatives");
			builder.put(grammarAccess.getTimeCondAccess().getAlternatives_1(), "rule__TimeCond__Alternatives_1");
			builder.put(grammarAccess.getRelOpAccess().getAlternatives(), "rule__RelOp__Alternatives");
			builder.put(grammarAccess.getApplianceTypeAccess().getAlternatives(), "rule__ApplianceType__Alternatives");
			builder.put(grammarAccess.getDeclarationAccess().getGroup(), "rule__Declaration__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_6(), "rule__Rule__Group_6__0");
			builder.put(grammarAccess.getTurnActionAccess().getGroup(), "rule__TurnAction__Group__0");
			builder.put(grammarAccess.getSetActionAccess().getGroup(), "rule__SetAction__Group__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup(), "rule__OrExpr__Group__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1(), "rule__OrExpr__Group_1__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup(), "rule__AndExpr__Group__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1(), "rule__AndExpr__Group_1__0");
			builder.put(grammarAccess.getPrimAccess().getGroup_3(), "rule__Prim__Group_3__0");
			builder.put(grammarAccess.getTimeCondAccess().getGroup(), "rule__TimeCond__Group__0");
			builder.put(grammarAccess.getTimeCondAccess().getGroup_1_0(), "rule__TimeCond__Group_1_0__0");
			builder.put(grammarAccess.getTimeCondAccess().getGroup_1_1(), "rule__TimeCond__Group_1_1__0");
			builder.put(grammarAccess.getPriceCondAccess().getGroup(), "rule__PriceCond__Group__0");
			builder.put(grammarAccess.getOccCondAccess().getGroup(), "rule__OccCond__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getDeclarationAccess().getNameAssignment_1(), "rule__Declaration__NameAssignment_1");
			builder.put(grammarAccess.getDeclarationAccess().getTypeAssignment_3(), "rule__Declaration__TypeAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_3(), "rule__Rule__ConditionAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getThenActionAssignment_5(), "rule__Rule__ThenActionAssignment_5");
			builder.put(grammarAccess.getRuleAccess().getElseActionAssignment_6_1(), "rule__Rule__ElseActionAssignment_6_1");
			builder.put(grammarAccess.getTurnActionAccess().getApplianceAssignment_1(), "rule__TurnAction__ApplianceAssignment_1");
			builder.put(grammarAccess.getTurnActionAccess().getActionAssignment_2(), "rule__TurnAction__ActionAssignment_2");
			builder.put(grammarAccess.getSetActionAccess().getApplianceAssignment_1(), "rule__SetAction__ApplianceAssignment_1");
			builder.put(grammarAccess.getSetActionAccess().getValueAssignment_3(), "rule__SetAction__ValueAssignment_3");
			builder.put(grammarAccess.getExprAccess().getOrExprAssignment(), "rule__Expr__OrExprAssignment");
			builder.put(grammarAccess.getOrExprAccess().getLeftAssignment_0(), "rule__OrExpr__LeftAssignment_0");
			builder.put(grammarAccess.getOrExprAccess().getRightAssignment_1_1(), "rule__OrExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getAndExprAccess().getLeftAssignment_0(), "rule__AndExpr__LeftAssignment_0");
			builder.put(grammarAccess.getAndExprAccess().getRightAssignment_1_1(), "rule__AndExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getPrimAccess().getTimeCondAssignment_0(), "rule__Prim__TimeCondAssignment_0");
			builder.put(grammarAccess.getPrimAccess().getPriceCondAssignment_1(), "rule__Prim__PriceCondAssignment_1");
			builder.put(grammarAccess.getPrimAccess().getOccCondAssignment_2(), "rule__Prim__OccCondAssignment_2");
			builder.put(grammarAccess.getPrimAccess().getSubExprAssignment_3_1(), "rule__Prim__SubExprAssignment_3_1");
			builder.put(grammarAccess.getTimeCondAccess().getTimeAssignment_1_0_1(), "rule__TimeCond__TimeAssignment_1_0_1");
			builder.put(grammarAccess.getTimeCondAccess().getStartAssignment_1_1_1(), "rule__TimeCond__StartAssignment_1_1_1");
			builder.put(grammarAccess.getTimeCondAccess().getEndAssignment_1_1_3(), "rule__TimeCond__EndAssignment_1_1_3");
			builder.put(grammarAccess.getPriceCondAccess().getOpAssignment_1(), "rule__PriceCond__OpAssignment_1");
			builder.put(grammarAccess.getPriceCondAccess().getValueAssignment_2(), "rule__PriceCond__ValueAssignment_2");
			builder.put(grammarAccess.getOccCondAccess().getOpAssignment_1(), "rule__OccCond__OpAssignment_1");
			builder.put(grammarAccess.getOccCondAccess().getValueAssignment_2(), "rule__OccCond__ValueAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private HemDslGrammarAccess grammarAccess;

	@Override
	protected InternalHemDslParser createParser() {
		InternalHemDslParser result = new InternalHemDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HemDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HemDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
