/*
 * generated by Xtext 2.38.0
 */
package org.homeenergy.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.homeenergy.parser.antlr.internal.InternalHemDslParser;
import org.homeenergy.services.HemDslGrammarAccess;

public class HemDslParser extends AbstractAntlrParser {

	@Inject
	private HemDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHemDslParser createParser(XtextTokenStream stream) {
		return new InternalHemDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HemDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HemDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
